# Generated by Django 6.0.5 on 2026-07-26 15:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('objet_type', models.CharField(max_length=100)),
                ('objet_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cimetiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('pays', models.CharField(blank=True, default='République du Congo', max_length=100)),
                ('quartier', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('limite_nord', models.FloatField(blank=True, null=True, verbose_name='Latitude limite Nord')),
                ('limite_sud', models.FloatField(blank=True, null=True, verbose_name='Latitude limite Sud')),
                ('limite_est', models.FloatField(blank=True, null=True, verbose_name='Longitude limite Est')),
                ('limite_ouest', models.FloatField(blank=True, null=True, verbose_name='Longitude limite Ouest')),
                ('superficie_totale', models.FloatField(default=0, verbose_name='Superficie totale (m²)')),
                ('tombeau_longueur', models.FloatField(default=2.5, verbose_name="Longueur standard d'un tombeau (m)")),
                ('tombeau_largeur', models.FloatField(default=1.2, verbose_name="Largeur standard d'un tombeau (m)")),
                ('nombre_places_estime', models.IntegerField(default=0)),
                ('mot_de_passe_acces', models.CharField(max_length=128, verbose_name="Mot de passe d'accès (haché)")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('admin_createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cimetieres_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Caveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('section', models.CharField(max_length=10)),
                ('bloc', models.CharField(max_length=10)),
                ('type_caveau', models.CharField(choices=[('simple', 'Simple (1 place)'), ('double', 'Double (2 places)'), ('familial', 'Familial (4+ places)')], default='simple', max_length=20)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('occupe', 'Occupé'), ('non_exploitable', 'Non exploitable')], default='disponible', max_length=20)),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('cimetiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caveaux', to='gestion.cimetiere')),
            ],
        ),
        migrations.CreateModel(
            name='CodeInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('role_autorise', models.CharField(choices=[('agent', 'Agent de terrain'), ('secretariat', 'Secretariat')], max_length=20)),
                ('utilise', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_utilisation', models.DateTimeField(blank=True, null=True)),
                ('cimetiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_invitation', to='gestion.cimetiere')),
                ('utilise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_utilises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_concession', models.CharField(choices=[('temporaire', 'Temporaire'), ('perpetuelle', 'Perpétuelle')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('renouvele', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('beneficiaire', models.CharField(blank=True, default='', max_length=200, verbose_name='Bénéficiaire')),
                ('montant', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('caveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='gestion.caveau')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Defunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, default='', max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_deces', models.DateField()),
                ('caveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defunts', to='gestion.caveau')),
            ],
        ),
        migrations.CreateModel(
            name='Exhumation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('demande', 'Demande'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='demande', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('caveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.caveau')),
                ('defunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.defunt')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='', max_length=100)),
                ('prenom', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('agent', 'Agent de terrain'), ('secretariat', 'Secretariat'), ('client', 'Client')], default='client', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Valide'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('code_mfa', models.CharField(blank=True, max_length=6, null=True)),
                ('code_mfa_date', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ville', models.CharField(blank=True, default='', max_length=100, verbose_name='Ville de résidence')),
                ('cimetiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='gestion.cimetiere')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('client_prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('type_caveau', models.CharField(default='simple', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=0, default=750000, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('annulee', 'Annulée'), ('payee', 'Payée')], default='en_attente', max_length=20)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('caveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gestion.caveau')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_creees', to=settings.AUTH_USER_MODEL)),
                ('defunt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.defunt')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_reservation'],
            },
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=64, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_utilisation', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
