# Generated by Django 6.0.5 on 2026-07-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profil',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
