# Generated by Django 6.0.5 on 2026-07-29 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_profil_photo_profil_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='montant_paye',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('methode', models.CharField(choices=[('airtel_money', 'Airtel Money'), ('mtn_money', 'MTN Money'), ('mpesa', 'M-Pesa'), ('especes', 'Espèces'), ('virement', 'Virement bancaire')], max_length=20)),
                ('numero_telephone', models.CharField(blank=True, default='', max_length=20)),
                ('reference_transaction', models.CharField(max_length=50, unique=True)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gestion.reservation')),
            ],
        ),
    ]
