# Generated by Django 6.0.5 on 2026-07-29 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_reservation_montant_paye_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exhumation',
            name='date_realisation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='date_souhaitee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='document_legal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhumations_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exhumation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('realisee', 'Réalisée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
